spring:
  application:
    name: sync-play
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 851961308168-as92ju958vskp8ei9figiv0fupqha1ov.apps.googleusercontent.com
            client-secret: ${GOOGLE_CLIENT_SECRET}
            scope: openid
            redirect-uri: "http://localhost:8080/login/oauth2/code/google"
        provider:
          google:
            authorization-uri: https://accounts.google.com/o/oauth2/auth
            token-uri: https://oauth2.googleapis.com/token
            user-info-uri: https://www.googleapis.com/oauth2/v3/userinfo
  datasource:
    url: jdbc:postgresql://localhost:5432/piglets
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
